# Generated by Django 6.0.5 on 2026-05-09 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def fix_cashier_fk(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    cursor = schema_editor.connection.cursor()
    cursor.execute("SELECT id, cashier FROM sales_order")
    rows = cursor.fetchall()

    for row_id, cashier_val in rows:
        if cashier_val and not str(cashier_val).isdigit():
            try:
                user = User.objects.get(username=cashier_val)
                cursor.execute(
                    "UPDATE sales_order SET cashier = %s WHERE id = %s",
                    [user.id, row_id]
                )
            except User.DoesNotExist:
                cursor.execute(
                    "UPDATE sales_order SET cashier = NULL WHERE id = %s",
                    [row_id]
                )


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(fix_cashier_fk, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='cashier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('open', 'បើក'), ('completed', 'បានបញ្ចប់'), ('cancelled', 'បានលុបចោល')], default='open', max_length=20),
        ),
    ]